// ==>  splice (+)
// ==>  includes (+)
// ==>  lastIndexOf (+)
// ==>  split (+)
// ==>  slice (+)
// ==>  indexOf (+)
// ==>  shift (+)
// ==>  unshift (+)
// ==>  toString (+)
// ==>  pop (+)
// ==>  push (+)
// ==>  concat (+)
// ==>  join (+)
// -------------------
// ==>  reverse (-)
// ==>  sort (-)
// ==>  forEach (-)
// ==>  forEach (-)
// ==>  map (-)
// ==>  filter (-)
// ==>  find (-)
// ==>  findIndex (-)
// ==>  every (-)
// ==>  some (-)
// ==>  at (-)
// ==>  reduce (-)

